### ISSUE TITLE
positiontoindex(p, l) error

### ISSUE THREAD

**Issue by jablauvelt** [ChrisRackauckas/LinkedLists.jl#5]
First of all, thanks for creating this package! This is great. I think this issue might be a quick fix - see reproducible example here:
```
using LinkedLists

lst = LinkedList{Int64}()
append!(lst, [1, 3, 5])
positiontoindex(2, lst)

ERROR: MethodError: no method matching getindex(::LinkedLists.ListIndexIterator{LinkedList{Int64}}, ::Int64)
Stacktrace:
 [1] positiontoindex(::Int64, ::LinkedList{Int64}) at C:\Users\JG814FX\.julia\packages\LinkedLists\Rqp8Q\src\list.jl:302
 [2] top-level scope at none:0
```

While I'm here, b/c it's sort of related - running `collect(keys)` doesn't work because length() isn't defined for length(::LinkedLists.ListIndexIterator{LinkedList{Int64}}). I suppose using collect() directly isn't usually ideal but it's helpful for debugging and so forth - if it's a quick change, might be useful.

Lastly, if you don't have time to look at this, I could try submitting a pull request. I'm still new to Julia but happy to help!

**Comment by ChrisRackauckas** [comment]
Thanks for the report! Sorry it took so long to get to this. I added a length for the keys iterator as well.

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()
