### ISSUE TITLE
`Base.last` is not O(1), against Base documentation

### ISSUE THREAD

**Issue by henriquebecker91** [ChrisRackauckas/LinkedLists.jl#9]
At least since Julia 1.0, [the `Base.last` documentaion](https://docs.julialang.org/en/v1.0/base/collections/#Base.last) says:

> Get the last element of an ordered collection, if it can be computed in O(1) time.

So the [`function last(l::AbstractList)`](https://github.com/ChrisRackauckas/LinkedLists.jl/blob/master/src/list.jl#L126--L132) is not conformant. At the very least I think we ought to create a separate documentation for this method, contradicting the generic `Base.last` documentation. Better alternatives, are not extending `Base.last` but providing a `LinkedLists.last`, or giving it another name, or just removing this specialization.

I can implement and test any of the three solutions, I just need the maintainer's decision.

**Comment by knuesel** [comment]
Context: https://discourse.julialang.org/t/getting-the-last-element-of-an-iterator/49696/17

**Comment by ChrisRackauckas** [comment]
Docs I guess. Not implementing it because it doesn't hit O(1) is kind of silly. That should be a trait.
